image: Visual Studio 2013
shallow_clone: true
clone_depth: 1
environment:
  matrix:
  - MSYSTEM: MINGW64
    BASH_PATH: C:\msys64\usr\bin\bash
#  - BASH_PATH: c:\cygwin\bin\bash


build_script:
- appveyor AddMessage Building -Category Information
- cmd: '%BASH_PATH% -lc "cd $APPVEYOR_BUILD_FOLDER; autoreconf -i && ./configure && make"'

after_build:
- appveyor AddMessage Installing -Category Information
- '%BASH_PATH% -lc "cd $APPVEYOR_BUILD_FOLDER; make install-strip DESTDIR=/c/inst"'
- '%BASH_PATH% -lc "cd /mingw64/bin && cp libgcc_s_seh-1.dll libiconv-2.dll libintl-8.dll libstdc++-6.dll libwinpthread-1.dll /c/inst/mingw64/bin/"'
- appveyor AddMessage Packing -Category Information
- 7z.exe a -tzip -mx9 -mmt %APPVEYOR_BUILD_FOLDER%\hunspell-mingw64.zip C:\inst\mingw64\*

test_script:
- appveyor AddMessage Testing -Category Information
- appveyor AddTest Regression -Framework catch -FileName stuff -Outcome Running
- set Outcome=Passed
- '%BASH_PATH% -lc "env"'
- '%BASH_PATH% -lc "cd $APPVEYOR_BUILD_FOLDER; make check" || set Outcome=Failed'
- appveyor UpdateTest Regression -Framework catch -FileName stuff -Outcome %Outcome% -Duration 1
- if not %Outcome%==Passed type tests\v1cmdline\test-suite.log

artifacts:
- path: hunspell-mingw64.zip
- path: tests/v1cmdline/test-suite.log

# TODO https://www.appveyor.com/docs/deployment/github/
